---

#- name: Nvidia-Docker | ensure nvidia-docker repository public key is installed
#  shell: "curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -"
#  register: result
#  until: result | succeeded
#  retries: 5
#  delay: 5
#  # when: inventory_hostname in nvidia_gpu_nodes
#
#- name: Nvidia-Docker |ensure nvidia-docker repository is enabled
#  shell: >
#    curl -s -L https://nvidia.github.io/nvidia-docker/$(. /etc/os-release;echo $ID$VERSION_ID)/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
#  register: result
#  until: result | succeeded
#  retries: 5
#  delay: 5
#  # when: inventory_hostname in nvidia_gpu_nodes

- name: Nvidia-Docker |ensure docker is stopped
  service:
    name: docker
    state: stopped
  # when: inventory_hostname in nvidia_gpu_nodes

- name: Nvidia-Docker |ensure nvidia-container-runtime are installed
  apt:
    name: nvidia-container-runtime=2.0.0+docker18.09.7-3
    update_cache: yes
  register: result
  until: result | succeeded
  retries: 5
  delay: 5
  # when: inventory_hostname in nvidia_gpu_nodes

- name: Nvidia-Docker |ensure nvidia-docker are installed
  apt:
    name: nvidia-docker2=2.0.3+docker18.09.7-3
    update_cache: yes
  register: result
  until: result | succeeded
  retries: 5
  delay: 5
  # when: inventory_hostname in nvidia_gpu_nodes

- name: Nvidia-Docker |ensure docker daemon.json is absent
  file:
    path: /etc/docker/daemon.json
    state: absent
